version: '3'
services:
  php:
    build: .
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - "/data/fpm-project:/var/www/html"
      - "/data/php/log:/var/log/php"
    container_name: "php-fpm"