# 拦截 HTTP (80端口) 的 IP 直连访问
server {
    listen 80 default_server;
    server_name _;
    return 444;
}

# 拦截 HTTPS (443端口) 的 IP 直连访问，保护证书不泄露
server {
    listen 443 default_server ssl;
    server_name _;
    # 核心指令：直接拒绝 SSL 握手
    ssl_reject_handshake on;
    # 捕获 HTTP 访问 HTTPS 端口的内部特征码 (497)
    error_page 497 =444 @close;
    # 丢入黑洞无故断开
    location @close {
        return 444;
    }
}
