version: '3'
services:
      frps:
        build: .
        # 端口映射  根据需要自行调整
        ports:
          - "7000:7000"
          - "2223-2260:2223-2260"
        restart: always
        # 配置文件
        volumes:
          - "$PWD/conf:/frp/conf"
        # 容器名称
        container_name: "frps"