version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "$PWD/code:/var/www/html"
      - "$PWD/cert:/cert"
      - "$PWD/conf:/etc/nginx/conf.d"
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/logs:/var/log/nginx"
    container_name: "nginx"