version: '3'
services:
  openvpn:
    # privileged: true
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn