version: '3'
services:
  yapi:
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./yapi/config.json:/yapi/config.json"
      - "./yapi/log:/yapi/log"
    container_name: "yapi"